dist: trusty
language:
  - cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
script:
  # Export CC and CXX to tell cmake which compiler to use
  - if [ "$CC" = "gcc" ]; then export CC=/usr/bin/gcc-7; fi
  - if [ "$CXX" = "g++" ]; then export CXX=/usr/bin/g++-7; fi
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tracerz
  - cd ..
  - rm -R build